// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AchieveGoal(arg1) {
  return window['go']['main']['App']['AchieveGoal'](arg1);
}

export function AddNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNote'](arg1, arg2, arg3);
}

export function AddReward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddReward'](arg1, arg2, arg3, arg4, arg5);
}

export function AutoPauseInactiveActivities(arg1, arg2) {
  return window['go']['main']['App']['AutoPauseInactiveActivities'](arg1, arg2);
}

export function CreateActivity(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateActivity'](arg1, arg2, arg3);
}

export function CreateChild(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateChild'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateFlashcard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFlashcard'](arg1, arg2, arg3, arg4);
}

export function CreateGoal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateGoal'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNoteTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNoteTemplate'](arg1, arg2, arg3);
}

export function DeleteChild(arg1) {
  return window['go']['main']['App']['DeleteChild'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteNoteTemplate(arg1) {
  return window['go']['main']['App']['DeleteNoteTemplate'](arg1);
}

export function EndActivityInSession(arg1, arg2) {
  return window['go']['main']['App']['EndActivityInSession'](arg1, arg2);
}

export function EndSession(arg1, arg2) {
  return window['go']['main']['App']['EndSession'](arg1, arg2);
}

export function GenerateSessionSummary(arg1) {
  return window['go']['main']['App']['GenerateSessionSummary'](arg1);
}

export function GetActiveActivitiesInSession(arg1) {
  return window['go']['main']['App']['GetActiveActivitiesInSession'](arg1);
}

export function GetActiveSession(arg1) {
  return window['go']['main']['App']['GetActiveSession'](arg1);
}

export function GetActivityByID(arg1) {
  return window['go']['main']['App']['GetActivityByID'](arg1);
}

export function GetAllActivities() {
  return window['go']['main']['App']['GetAllActivities']();
}

export function GetAllChildren() {
  return window['go']['main']['App']['GetAllChildren']();
}

export function GetAllNoteTemplates() {
  return window['go']['main']['App']['GetAllNoteTemplates']();
}

export function GetChildByID(arg1) {
  return window['go']['main']['App']['GetChildByID'](arg1);
}

export function GetChildGoals(arg1) {
  return window['go']['main']['App']['GetChildGoals'](arg1);
}

export function GetChildProgressSummary(arg1) {
  return window['go']['main']['App']['GetChildProgressSummary'](arg1);
}

export function GetChildRewards(arg1) {
  return window['go']['main']['App']['GetChildRewards'](arg1);
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetFlashcardsByCategory(arg1) {
  return window['go']['main']['App']['GetFlashcardsByCategory'](arg1);
}

export function GetRewardSummary(arg1) {
  return window['go']['main']['App']['GetRewardSummary'](arg1);
}

export function GetSessionActivities(arg1) {
  return window['go']['main']['App']['GetSessionActivities'](arg1);
}

export function GetSessionActivityHistoryByChild(arg1) {
  return window['go']['main']['App']['GetSessionActivityHistoryByChild'](arg1);
}

export function GetSessionByID(arg1) {
  return window['go']['main']['App']['GetSessionByID'](arg1);
}

export function GetSessionNotes(arg1) {
  return window['go']['main']['App']['GetSessionNotes'](arg1);
}

export function GetSessionProgress(arg1) {
  return window['go']['main']['App']['GetSessionProgress'](arg1);
}

export function GetSessionsByChild(arg1) {
  return window['go']['main']['App']['GetSessionsByChild'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogFlashcardResponse(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogFlashcardResponse'](arg1, arg2, arg3, arg4);
}

export function StartActivityInSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartActivityInSession'](arg1, arg2, arg3);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function UpdateActivityInSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateActivityInSession'](arg1, arg2);
}

export function UpdateChild(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateChild'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}

export function UpdateNoteTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNoteTemplate'](arg1, arg2, arg3, arg4);
}

export function UpdateSessionSummaryNotes(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionSummaryNotes'](arg1, arg2);
}

export function ValidateSession(arg1) {
  return window['go']['main']['App']['ValidateSession'](arg1);
}
